var PLATFORMS_DATA = [
  {
    "id": "plat-1",
    "name": "FutureLearn",
    "description": "منصة تعليمية بريطانية تابعة لمجموعة الجامعات العالمية. تقدم آلاف الدورات المجانية والمدفوعة في مجالات متنوعة مع شهادات إتمام.",
    "description_en": "A British educational platform from a global university alliance. Offers thousands of free and paid courses across diverse fields with completion certificates.",
    "description_tr": "K\u00fcresel \u00fcniversite grubuna ba\u011fl\u0131 bir Britanya e\u011fitim platformu. \u00c7e\u015fitli alanlarda binlerce \u00fccretsiz ve \u00fccretli kurs sunar.",
    "category": "تعليم",
    "platform": "FutureLearn",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://www.futurelearn.com/courses",
    "thumbnail": "https://www.google.com/s2/favicons?domain=futurelearn.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-2",
    "name": "Agora",
    "description": "منصة تعليمية تابعة لليونيسف (UNICEF) تقدم دورات مجانية في مجالات حماية الطفل، التعليم، الصحة، التنمية المستدامة، والعمل الإنساني.",
    "description_en": "A UNICEF educational platform offering free courses in child protection, education, health, sustainable development, and humanitarian work.",
    "description_tr": "UNICEF'e ba\u011fl\u0131 bir e\u011fitim platformu. \u00c7ocuk koruma, e\u011fitim, sa\u011fl\u0131k, s\u00fcrd\u00fcr\u00fclebilir kalk\u0131nma ve insani yard\u0131m alanlar\u0131nda \u00fccretsiz kurslar sunar.",
    "category": "تعليم",
    "platform": "Agora",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "متعدد اللغات",
    "link": "https://agora.unicef.org/local/catalogue/index.php?filters[]=133",
    "thumbnail": "https://www.google.com/s2/favicons?domain=unicef.org&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-3",
    "name": "IBM Skills Build",
    "description": "منصة IBM المجانية لتطوير المهارات التقنية. تغطي الذكاء الاصطناعي، الحوسبة السحابية، الأمن السيبراني، علوم البيانات، وتقنية المعلومات. تقدم شهادات معتمدة.",
    "description_en": "IBM's free platform for technical skill development. Covers AI, cloud computing, cybersecurity, data science, and IT. Offers accredited certificates.",
    "description_tr": "IBM'nin teknik beceri geli\u015ftirme i\u00e7in \u00fccretsiz platformu. Yapay zeka, bulut bili\u015fim, siber g\u00fcvenlik, veri bilimi ve BT alanlar\u0131n\u0131 kapsar.",
    "category": "تكنولوجيا",
    "platform": "IBM Skills Build",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "متعدد اللغات",
    "link": "https://skillsbuild.org/college-students/course-catalog",
    "thumbnail": "https://www.google.com/s2/favicons?domain=skillsbuild.org&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-4",
    "name": "Forage",
    "description": "منصة فريدة تقدم تجارب عمل افتراضية من شركات عالمية مثل JPMorgan وBCG. تمكنك من اكتساب خبرة عملية حقيقية وبناء سيرتك الذاتية.",
    "description_en": "A unique platform offering virtual work experience from global companies like JPMorgan and BCG. Gain real practical experience and build your resume.",
    "description_tr": "JPMorgan ve BCG gibi k\u00fcresel \u015firketlerden sanal i\u015f deneyimleri sunan benzersiz bir platform. Ger\u00e7ek pratik deneyim kazan\u0131n ve \u00f6zge\u00e7mi\u015finizi olu\u015fturun.",
    "category": "تسويق وأعمال",
    "platform": "Forage",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://www.theforage.com/virtual-internships",
    "thumbnail": "https://www.google.com/s2/favicons?domain=theforage.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-5",
    "name": "Microsoft",
    "description": "منصة مايكروسوفت للتعلم الرسمية. تقدم دورات مجانية ومدفوعة في Azure، Microsoft 365، Power Platform، الأمن السيبراني، والذكاء الاصطناعي مع شهادات معتمدة.",
    "description_en": "Microsoft's official learning platform. Offers free and paid courses in Azure, Microsoft 365, Power Platform, cybersecurity, and AI with accredited certificates.",
    "description_tr": "Microsoft'un resmi \u00f6\u011frenme platformu. Azure, Microsoft 365, Power Platform, siber g\u00fcvenlik ve yapay zeka alanlar\u0131nda \u00fccretsiz ve \u00fccretli kurslar sunar.",
    "category": "تكنولوجيا",
    "platform": "Microsoft",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "عربي/إنجليزي",
    "link": "https://learn.microsoft.com/en-us/training/browse/",
    "thumbnail": "https://www.google.com/s2/favicons?domain=microsoft.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-6",
    "name": "ITU Academy",
    "description": "أكاديمية الاتحاد الدولي للاتصالات (ITU) التابعة للأمم المتحدة. تقدم دورات في الاتصالات، الأمن السيبراني، الذكاء الاصطناعي، والسياسات الرقمية.",
    "description_en": "The International Telecommunication Union (ITU) Academy, a UN agency. Offers courses in telecommunications, cybersecurity, AI, and digital policies.",
    "description_tr": "Birle\u015fmi\u015f Milletler'e ba\u011fl\u0131 ITU Akademisi. Telekom\u00fcnikasyon, siber g\u00fcvenlik, yapay zeka ve dijital politikalar alanlar\u0131nda kurslar sunar.",
    "category": "تكنولوجيا",
    "platform": "ITU Academy",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "متعدد اللغات",
    "link": "https://academy.itu.int/training-courses/full-catalogue",
    "thumbnail": "https://academy.itu.int/themes/custom/itu_academy/src/assets/images/logos/ITU-logo.svg",
    "startDate": ""
  },
  {
    "id": "plat-7",
    "name": "Edx",
    "description": "منصة تعليمية رائدة تأسست من Harvard وMIT. تقدم آلاف الدورات من أفضل الجامعات العالمية. يمكنك الاستماع للدورات مجاناً ولكن تحتاج دفع مالي للحصول على الشهادة.",
    "description_en": "A leading educational platform founded by Harvard and MIT. Offers thousands of courses from top global universities. Audit for free, pay for certificates.",
    "description_tr": "Harvard ve MIT taraf\u0131ndan kurulan \u00f6nc\u00fc bir e\u011fitim platformu. En iyi \u00fcniversitelerden binlerce kurs sunar. \u00dccretsiz dinleyin, sertifika i\u00e7in \u00f6deme yap\u0131n.",
    "category": "تعليم",
    "platform": "Edx",
    "free": true,
    "certificate": false,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://www.edx.org/courses",
    "thumbnail": "https://www.google.com/s2/favicons?domain=edx.org&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-8",
    "name": "Code Academy",
    "description": "منصة تفاعلية لتعلم البرمجة. تقدم مسارات تعليمية في Python، JavaScript، HTML/CSS، SQL، وغيرها مع بيئة تدريب تفاعلية.",
    "description_en": "An interactive platform for learning programming. Offers learning paths in Python, JavaScript, HTML/CSS, SQL, and more with an interactive coding environment.",
    "description_tr": "Programlama \u00f6\u011frenmek i\u00e7in etkile\u015fimli bir platform. Python, JavaScript, HTML/CSS, SQL ve daha fazlas\u0131nda \u00f6\u011frenme yollar\u0131 sunar.",
    "category": "برمجة وبيانات",
    "platform": "Code Academy",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://www.codecademy.com/catalog",
    "thumbnail": "https://www.google.com/s2/favicons?domain=codecademy.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-9",
    "name": "Unitar",
    "description": "منصة تعليمية تابعة لمعهد الأمم المتحدة للتدريب والبحث (UNITAR). تقدم دورات في التنمية المستدامة، الدبلوماسية، إدارة الأزمات، والقيادة.",
    "description_en": "An educational platform from the UN Institute for Training and Research (UNITAR). Offers courses in sustainable development, diplomacy, crisis management, and leadership.",
    "description_tr": "Birle\u015fmi\u015f Milletler E\u011fitim ve Ara\u015ft\u0131rma Enstit\u00fcs\u00fc'ne (UNITAR) ba\u011fl\u0131 bir e\u011fitim platformu. S\u00fcrd\u00fcr\u00fclebilir kalk\u0131nma, diplomasi, kriz y\u00f6netimi ve liderlik kurslar\u0131 sunar.",
    "category": "تعليم",
    "platform": "Unitar",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "متعدد اللغات",
    "link": "https://event.unitar.org/full-catalog?search=&type%5B3%5D=3&price%5Bmin%5D=0&price%5Bmax%5D=96591&date%5Bmin%5D=&date%5Bmax%5D=&quick_filter=all",
    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ73nI5R5jGuTI2qnICsNl6aBz0o_5Hf5ET5w&s",
    "startDate": ""
  },
  {
    "id": "plat-10",
    "name": "Huawei",
    "description": "أكاديمية هواوي الرسمية. تقدم دورات مجانية في الشبكات، الذكاء الاصطناعي، الحوسبة السحابية، الأمن السيبراني، وإنترنت الأشياء مع شهادات معتمدة.",
    "description_en": "The official Huawei Academy. Offers free courses in networking, AI, cloud computing, cybersecurity, and IoT with accredited certificates.",
    "description_tr": "Resmi Huawei Akademisi. A\u011f, yapay zeka, bulut bili\u015fim, siber g\u00fcvenlik ve IoT alanlar\u0131nda \u00fccretsiz kurslar sunar.",
    "category": "تكنولوجيا",
    "platform": "Huawei",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "عربي/إنجليزي",
    "link": "https://e.huawei.com/en/talent/learning/#/home",
    "thumbnail": "https://www.google.com/s2/favicons?domain=huawei.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-11",
    "name": "openlearn.aucegypt.edu",
    "description": "تقدم الصفحة مساراً تعليمياً متكاملاً لتعلم اللغة الإنجليزية، مُصمم ليغطي جميع المستويات من المبتدئ حتى المتقدم، مع تركيز خاص على التحضير للدراسة الجامعية. وكذلك لديها دورات في مجالات أخرى مثل التعليم والحضارات.",
    "description_en": "Offers a complete learning path for English, designed for all levels from beginner to advanced, with a focus on university preparation. Also has courses in other fields like education and civilizations.",
    "description_tr": "ingilizce \u00f6\u011frenmek i\u00e7in ba\u015flang\u0131\u00e7tan ileri seviyeye kadar t\u00fcm seviyeleri kapsayan, \u00fcniversite haz\u0131rl\u0131\u011f\u0131na odaklanan eksiksiz bir \u00f6\u011frenme yolu sunar. E\u011fitim ve medeniyetler gibi di\u011fer alanlarda da kurslar\u0131 vard\u0131r.",
    "category": "لغات",
    "platform": "openlearn.aucegypt.edu",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://openlearn.aucegypt.edu/course/index.php?categoryid=2",
    "thumbnail": "https://openlearn.aucegypt.edu/pluginfile.php/1/theme_remui/faviconurl/1767874770/favicon.svg",
    "startDate": ""
  },
  {
    "id": "plat-12",
    "name": "HP Life",
    "description": "منصة HP للتعلم مدى الحياة. تقدم دورات مجانية في ريادة الأعمال، التسويق الرقمي، المهارات المالية، وتكنولوجيا المعلومات.",
    "description_en": "HP's lifelong learning platform. Offers free courses in entrepreneurship, digital marketing, financial skills, and IT.",
    "description_tr": "HP'nin ya\u015fam boyu \u00f6\u011frenme platformu. Giri\u015fimcilik, dijital pazarlama, finansal beceriler ve BT alanlar\u0131nda \u00fccretsiz kurslar sunar.",
    "category": "تسويق وأعمال",
    "platform": "HP Life",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "متعدد اللغات",
    "link": "https://www.life-global.org/allcourses",
    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDNOFTTB0IX77-gTg6-9-NHcEriWC8Hc3NYQ&s",
    "startDate": ""
  },
  {
    "id": "plat-13",
    "name": "Nvidia",
    "description": "منصة إنفيديا الرائدة في الذكاء الاصطناعي وتعلم الآلة. تقدم دورات مجانية في التعلم العميق، CUDA، معالجة الصور، والذكاء الاصطناعي التوليدي. جميع الدورات مجانية ولكن دورة واحدة فقط بشهادة والباقي بدون شهادات.",
    "description_en": "Nvidia's leading platform for AI and machine learning. Offers free courses in deep learning, CUDA, image processing, and generative AI. All courses are free but only one offers a certificate.",
    "description_tr": "Yapay zeka ve makine \u00f6\u011freniminde Nvidia'n\u0131n \u00f6nc\u00fc platformu. Derin \u00f6\u011frenme, CUDA, g\u00f6r\u00fcnt\u00fc i\u015fleme ve \u00fcretken yapay zeka alanlar\u0131nda \u00fccretsiz kurslar sunar. T\u00fcm kurslar \u00fccretsizdir ancak yaln\u0131zca biri sertifika verir.",
    "category": "برمجة وبيانات",
    "platform": "Nvidia",
    "free": true,
    "certificate": false,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://www.nvidia.com/en-us/training/self-paced-courses/",
    "thumbnail": "https://www.google.com/s2/favicons?domain=nvidia.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-14",
    "name": "Cisco",
    "description": "أكاديمية سيسكو الرسمية. تقدم دورات في الشبكات (CCNA)، الأمن السيبراني، إنترنت الأشياء، وLinux مع شهادات معترف بها عالمياً.",
    "description_en": "The official Cisco Academy. Offers courses in networking (CCNA), cybersecurity, IoT, and Linux with globally recognized certificates.",
    "description_tr": "Resmi Cisco Akademisi. A\u011f (CCNA), siber g\u00fcvenlik, IoT ve Linux alanlar\u0131nda k\u00fcresel olarak tan\u0131nan sertifikalarla kurslar sunar.",
    "category": "تكنولوجيا",
    "platform": "Cisco",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "متعدد اللغات",
    "link": "https://www.netacad.com/catalogs/learn",
    "thumbnail": "https://www.cloudcommunications.com/hubfs/Imported_Blog_Media/Cisco-Nov-17-2023-05-40-40-6925-AM.png",
    "startDate": ""
  },
  {
    "id": "plat-15",
    "name": "Open Learn",
    "description": "منصة التعلم المفتوح التابعة للجامعة المفتوحة (Open University) في المملكة المتحدة. تقدم مئات الدورات الأكاديمية المجانية بالكامل مع شهادات إتمام.",
    "description_en": "The Open Learning platform from the Open University in the UK. Offers hundreds of fully free academic courses with completion certificates.",
    "description_tr": "BK'deki A\u00e7\u0131k \u00dcniversite'ye ba\u011fl\u0131 bir platform. Tamamen \u00fccretsiz y\u00fczlerce akademik kurs ve tamamlama sertifikalar\u0131 sunar.",
    "category": "تعليم",
    "platform": "Open Learn",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://www.open.edu/openlearn/free-courses/full-catalogue",
    "thumbnail": "https://www.google.com/s2/favicons?domain=open.edu&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-16",
    "name": "Google (Skillshop)",
    "description": "منصة جوجل الرسمية لبناء المهارات. تقدم دورات مجانية في Google Ads، Analytics، التسويق الرقمي، Android، والسحابة مع شهادات معتمدة.",
    "description_en": "Google's official skill-building platform. Offers free courses in Google Ads, Analytics, digital marketing, Android, and cloud with accredited certificates.",
    "description_tr": "Google'\u0131n resmi beceri geli\u015ftirme platformu. Google Ads, Analytics, dijital pazarlama, Android ve bulut alanlar\u0131nda \u00fccretsiz kurslar sunar.",
    "category": "تسويق وأعمال",
    "platform": "Google (Skillshop)",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "عربي/إنجليزي",
    "link": "https://skillshop.withgoogle.com/",
    "thumbnail": "https://www.google.com/s2/favicons?domain=google.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-17",
    "name": "Solo Learn",
    "description": "تطبيق ومنصة تفاعلية لتعلم البرمجة بلغة مبسطة. تدعم العديد من لغات البرمجة مثل Python، Java، C++، JavaScript وتتيح التعلم عبر الجوال.",
    "description_en": "An interactive app and platform for learning programming in a simplified way. Supports many languages like Python, Java, C++, JavaScript with mobile learning.",
    "description_tr": "Basitle\u015ftirilmi\u015f bir \u015fekilde programlama \u00f6\u011frenmek i\u00e7in etkile\u015fimli bir uygulama ve platform. Mobil \u00f6\u011frenme ile Python, Java, C++, JavaScript gibi bir\u00e7ok dili destekler.",
    "category": "برمجة وبيانات",
    "platform": "Solo Learn",
    "free": true,
    "certificate": false,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://www.sololearn.com/en/learn",
    "thumbnail": "https://www.google.com/s2/favicons?domain=sololearn.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-18",
    "name": "Research Academy",
    "description": "أكاديمية ELSEVIER للتدريب على البحث العلمي. تقدم دورات مجانية في الكتابة الأكاديمية، النشر العلمي، تحليل البيانات البحثية، وإدارة المراجع.",
    "description_en": "Elsevier's research training academy. Offers free courses in academic writing, scientific publishing, research data analysis, and reference management.",
    "description_tr": "Elsevier'in ara\u015ft\u0131rma e\u011fitim akademisi. Akademik yaz\u0131m, bilimsel yay\u0131nc\u0131l\u0131k, ara\u015ft\u0131rma veri analizi ve referans y\u00f6netimi alanlar\u0131nda \u00fccretsiz kurslar sunar.",
    "category": "تعليم",
    "platform": "Research Academy",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://researcheracademy.elsevier.com/learn",
    "thumbnail": "https://www.google.com/s2/favicons?domain=elsevier.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-19",
    "name": "W3 School",
    "description": "أشهر منصة مجانية لتعلم برمجة الويب. تقدم دروساً تفاعلية في HTML، CSS، JavaScript، Python، SQL، PHP وأكثر.",
    "description_en": "The most popular free platform for learning web programming. Offers interactive tutorials in HTML, CSS, JavaScript, Python, SQL, PHP and more.",
    "description_tr": "Web programlama \u00f6\u011frenmek i\u00e7in en pop\u00fcler \u00fccretsiz platform. HTML, CSS, JavaScript, Python, SQL, PHP ve daha fazlas\u0131nda etkile\u015fimli dersler sunar.",
    "category": "برمجة وبيانات",
    "platform": "W3 School",
    "free": true,
    "certificate": false,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://www.w3schools.com/where_to_start.asp",
    "thumbnail": "https://www.google.com/s2/favicons?domain=w3schools.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-20",
    "name": "Khan Academy",
    "description": "منصة تعليمية غير ربحية تقدم تعليماً مجانياً للجميع. تغطي الرياضيات، العلوم، البرمجة، التاريخ، والاقتصاد بمحتوى عالي الجودة.",
    "description_en": "A non-profit educational platform offering free education for everyone. Covers math, science, programming, history, and economics with high-quality content.",
    "description_tr": "Herkes i\u00e7in \u00fccretsiz e\u011fitim sunan kar amac\u0131 g\u00fctmeyen bir e\u011fitim platformu. Y\u00fcksek kaliteli i\u00e7erikle matematik, fen, programlama, tarih ve ekonomi konular\u0131n\u0131 kapsar.",
    "category": "تعليم",
    "platform": "Khan Academy",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "عربي/إنجليزي",
    "link": "https://www.khanacademy.org/",
    "thumbnail": "https://www.google.com/s2/favicons?domain=khanacademy.org&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-21",
    "name": "Free Udemy",
    "description": "أكبر منصة للدورات التعليمية عالمياً. تضم آلاف الدورات في جميع المجالات. بعض الدورات مجانية وأخرى مدفوعة بأسعار متفاوتة. يمكنك الحصول على دورات Udemy مجاناً عبر موقع DiscUdemy.",
    "description_en": "The world's largest marketplace for learning courses. Hosts thousands of courses in all fields. Some are free, others paid. Get Udemy courses free via DiscUdemy.",
    "description_tr": "D\u00fcnyan\u0131n en b\u00fcy\u00fck \u00f6\u011frenme kurs pazar\u0131. T\u00fcm alanlarda binlerce kurs bar\u0131nd\u0131r\u0131r. Baz\u0131lar\u0131 \u00fccretsiz, di\u011ferleri \u00fccretlidir. DiscUdemy \u00fczerinden Udemy kurslar\u0131n\u0131 \u00fccretsiz al\u0131n.",
    "category": "تعليم",
    "platform": "Free Udemy",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "عربي/إنجليزي",
    "link": "https://www.discudemy.com/",
    "thumbnail": "https://www.google.com/s2/favicons?domain=discudemy.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-22",
    "name": "Kaggle",
    "description": "منصة علم البيانات والذكاء الاصطناعي التابعة لجوجل. تقدم دورات مجانية، مسابقات، ومشاريع عملية في Python، التعلم الآلي، وتحليل البيانات.",
    "description_en": "Google's data science and AI platform. Offers free courses, competitions, and hands-on projects in Python, machine learning, and data analysis.",
    "description_tr": "Google'\u0131n veri bilimi ve yapay zeka platformu. Python, makine \u00f6\u011frenimi ve veri analizinde \u00fccretsiz kurslar, yar\u0131\u015fmalar ve uygulamal\u0131 projeler sunar.",
    "category": "برمجة وبيانات",
    "platform": "Kaggle",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://www.kaggle.com/learn",
    "thumbnail": "https://www.google.com/s2/favicons?domain=kaggle.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-23",
    "name": "GitHub Learn",
    "description": "منصة جيت هاب التعليمية. تقدم دورات تفاعلية مجانية في Git، GitHub، DevOps، وأتمتة workflows.",
    "description_en": "GitHub's learning platform. Offers free interactive courses in Git, GitHub, DevOps, and workflow automation.",
    "description_tr": "GitHub'\u0131n \u00f6\u011frenme platformu. Git, GitHub, DevOps ve i\u015f ak\u0131\u015f\u0131 otomasyonu alanlar\u0131nda \u00fccretsiz etkile\u015fimli kurslar sunar.",
    "category": "برمجة وبيانات",
    "platform": "GitHub Learn",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://skills.github.com/",
    "thumbnail": "https://www.google.com/s2/favicons?domain=github.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-24",
    "name": "Google Cloud",
    "description": "منصة جوجل كلاود التعليمية. تقدم دورات مجانية في الحوسبة السحابية، البيانات الضخمة، التعلم الآلي، وبنية الخدمات السحابية مع شهادات.",
    "description_en": "Google Cloud's learning platform. Offers free courses in cloud computing, big data, machine learning, and cloud architecture with certificates.",
    "description_tr": "Google Cloud \u00f6\u011frenme platformu. Bulut bili\u015fim, b\u00fcy\u00fck veri, makine \u00f6\u011frenimi ve bulut mimarisi alanlar\u0131nda \u00fccretsiz kurslar sunar.",
    "category": "تكنولوجيا",
    "platform": "Google Cloud",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://www.skills.google/",
    "thumbnail": "https://www.google.com/s2/favicons?domain=cloud.google.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-25",
    "name": "Free Code Camp",
    "description": "منصة غير ربحية لتعلم البرمجة مجاناً بالكامل. تقدم مسارات تعليمية في تطوير الويب، Python، التعلم الآلي، وعلوم البيانات مع شهادات مجانية.",
    "description_en": "A non-profit platform for learning programming completely free. Offers learning paths in web development, Python, machine learning, and data science with free certificates.",
    "description_tr": "Tamamen \u00fccretsiz programlama \u00f6\u011frenmek i\u00e7in kar amac\u0131 g\u00fctmeyen bir platform. Web geli\u015ftirme, Python, makine \u00f6\u011frenimi ve veri biliminde \u00fccretsiz sertifikalarla \u00f6\u011frenme yollar\u0131 sunar.",
    "category": "برمجة وبيانات",
    "platform": "Free Code Camp",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "عربي/إنجليزي",
    "link": "https://www.freecodecamp.org/learn",
    "thumbnail": "https://www.google.com/s2/favicons?domain=freecodecamp.org&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-26",
    "name": "Coursera",
    "description": "منصة تعليمية رائدة تقدم دورات من أفضل الجامعات والشركات. المحتوى مجاني بالكامل، ولكن تحتاج للدفع للحصول على الشهادة.",
    "description_en": "A leading educational platform from top universities and companies. Content is completely free to access, but you need to pay for the certificate.",
    "description_tr": "En iyi \u00fcniversitelerden ve \u015firketlerden kurslar sunan \u00f6nc\u00fc bir platform. \u0130\u00e7erik tamamen \u00fccretsizdir ancak sertifika i\u00e7in \u00f6deme yapman\u0131z gerekir.",
    "category": "تعليم",
    "platform": "Coursera",
    "free": true,
    "certificate": false,
    "duration": "",
    "level": "",
    "language": "عربي/إنجليزي",
    "link": "https://www.coursera.org/courses",
    "thumbnail": "https://www.google.com/s2/favicons?domain=coursera.org&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-27",
    "name": "Simple Learn",
    "description": "منصة تعليمية تقدم دورات في إدارة المشاريع، الأمن السيبراني، الذكاء الاصطناعي، وتحليل البيانات مع شهادات مهنية.",
    "description_en": "An educational platform offering courses in project management, cybersecurity, AI, and data analysis with professional certificates.",
    "description_tr": "Proje y\u00f6netimi, siber g\u00fcvenlik, yapay zeka ve veri analizi alanlar\u0131nda profesyonel sertifikalarla kurslar sunan bir e\u011fitim platformu.",
    "category": "تسويق وأعمال",
    "platform": "Simple Learn",
    "free": false,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://www.simplilearn.com/skillup-free-online-courses",
    "thumbnail": "https://www.google.com/s2/favicons?domain=simplilearn.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-28",
    "name": "Alison",
    "description": "منصة تعليم مجاني رائدة تقدم آلاف الدورات في مختلف المجالات مع شهادات مجانية. تغطي المهارات الوظيفية والتقنية والشخصية.",
    "description_en": "A leading free education platform offering thousands of courses across various fields with free certificates. Covers job, technical, and personal skills.",
    "description_tr": "Binlerce kursta \u00fccretsiz sertifikalar sunan \u00f6nc\u00fc bir \u00fccretsiz e\u011fitim platformu. \u0130\u015f, teknik ve ki\u015fisel becerileri kapsar.",
    "category": "تعليم",
    "platform": "Alison",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "عربي/إنجليزي",
    "link": "https://alison.com/courses",
    "thumbnail": "https://www.google.com/s2/favicons?domain=alison.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-29",
    "name": "Saylor",
    "description": "أكاديمية سايلور غير الربحية. تقدم دورات أكاديمية مجانية بالكامل تعادل المقررات الجامعية مع شهادات إتمام.",
    "description_en": "The non-profit Saylor Academy. Offers fully free academic courses equivalent to university-level courses with completion certificates.",
    "description_tr": "Kar amac\u0131 g\u00fctmeyen Saylor Akademisi. \u00dcniversite d\u00fczeyinde tamamen \u00fccretsiz akademik kurslar ve tamamlama sertifikalar\u0131 sunar.",
    "category": "تعليم",
    "platform": "Saylor",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://learn.saylor.org/course/index.php",
    "thumbnail": "https://www.google.com/s2/favicons?domain=saylor.org&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-30",
    "name": "سطر Satr",
    "name_en": "Satr",
    "name_tr": "Satr",
    "description": "منصة سعودية لتعلم البرمجة والتقنيات الحديثة باللغة العربية. تقدم دورات مجانية في لغات البرمجة والأمن السيبراني وقواعد البيانات.",
    "description_en": "A Saudi platform for learning programming and modern technologies in Arabic. Offers free courses in programming languages, cybersecurity, and databases.",
    "description_tr": "Arap\u00e7a programlama ve modern teknolojiler \u00f6\u011frenmek i\u00e7in bir Suudi platformu. Programlama dilleri, siber g\u00fcvenlik ve veritabanlar\u0131nda \u00fccretsiz kurslar sunar.",
    "category": "برمجة وبيانات",
    "platform": "سطر Satr",
    "platform_en": "Satr",
    "platform_tr": "Satr",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "عربي",
    "link": "https://satr.codes",
    "thumbnail": "https://www.google.com/s2/favicons?domain=satr.codes&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-31",
    "name": "إدراك Edraak",
    "name_en": "Edraak",
    "name_tr": "Edraak",
    "description": "منصة تعليمية عربية من مؤسسة الملكة رانيا للتعليم والتنمية. تقدم مساقات مجانية عبر الإنترنت باللغة العربية من أفضل الجامعات والخبراء العرب والعالميين مع شهادات إتمام.",
    "description_en": "An Arab educational platform from the Queen Rania Foundation. Offers free online courses in Arabic from top Arab and global universities and experts.",
    "description_tr": "Krali\u00e7e Rania Vakf\u0131'ndan bir Arap e\u011fitim platformu. En iyi Arap ve k\u00fcresel \u00fcniversitelerden Arap\u00e7a \u00fccretsiz \u00e7evrimi\u00e7i kurslar sunar.",
    "category": "تعليم",
    "platform": "إدراك Edraak",
    "platform_en": "Edraak",
    "platform_tr": "Edraak",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "عربي",
    "link": "https://www.edraak.org/explore/?type=course",
    "thumbnail": "https://www.google.com/s2/favicons?domain=edraak.org&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-32",
    "name": "معارف Maaref",
    "name_en": "Maaref",
    "name_tr": "Maaref",
    "description": "منصة عربية تضم آلاف الدورات المجانية في مختلف المجالات. تقدم دورات في البرمجة، اللغات، التصميم، الإدارة، والتسويق مع شهادات معتمدة.",
    "description_en": "An Arab platform with thousands of free courses across various fields. Offers courses in programming, languages, design, management, and marketing with accredited certificates.",
    "description_tr": "Binlerce \u00fccretsiz kursu olan bir Arap platformu. Programlama, diller, tasar\u0131m, y\u00f6netim ve pazarlama alanlar\u0131nda akredite sertifikalarla kurslar sunar.",
    "category": "تعليم",
    "platform": "معارف Maaref",
    "platform_en": "Maaref",
    "platform_tr": "Maaref",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "عربي",
    "link": "https://www.m3aarf.com/certified/courses",
    "thumbnail": "https://www.google.com/s2/favicons?domain=m3aarf.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-33",
    "name": "رواق Rwaq",
    "name_en": "Rwaq",
    "name_tr": "Rwaq",
    "description": "المنصة العربية للتعليم المفتوح. تقدم مواد أكاديمية مجانية باللغة العربية في شتى المجالات والتخصصات من محاضرين متطوعين. تمنح شهادات إتمام لبعض المواد.",
    "description_en": "The Arab open education platform. Offers free academic materials in Arabic across various fields from volunteer instructors. Grants completion certificates for some courses.",
    "description_tr": "Arap a\u00e7\u0131k e\u011fitim platformu. G\u00f6n\u00fcll\u00fc e\u011fitmenlerden \u00e7e\u015fitli alanlarda Arap\u00e7a \u00fccretsiz akademik materyaller sunar. Baz\u0131 dersler i\u00e7in tamamlama sertifikas\u0131 verir.",
    "category": "تعليم",
    "platform": "رواق Rwaq",
    "platform_en": "Rwaq",
    "platform_tr": "Rwaq",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "عربي",
    "link": "https://www.rwaq.org/courses",
    "thumbnail": "https://rwaq-production.s3.amazonaws.com/uploads/rwaq_image_params/platform-logo-sidebar.png",
    "startDate": ""
  },
  {
    "id": "plat-34",
    "name": "DataCamp",
    "description": "منصة متخصصة في تعلم علوم البيانات والذكاء الاصطناعي والتحليل الإحصائي. تقدم مئات الدورات التفاعلية والتمارين العملية بلغة Python وR وSQL وغيرها.",
    "description_en": "A specialized platform for learning data science, AI, and statistical analysis. Offers hundreds of interactive courses and hands-on exercises in Python, R, SQL, and more.",
    "description_tr": "Veri bilimi, yapay zeka ve istatistiksel analiz \u00f6\u011frenmek i\u00e7in \u00f6zel bir platform. Python, R, SQL ve daha fazlas\u0131nda y\u00fczlerce etkile\u015fimli kurs sunar.",
    "category": "برمجة وبيانات",
    "platform": "DataCamp",
    "free": false,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://www.datacamp.com/courses",
    "thumbnail": "https://www.google.com/s2/favicons?domain=datacamp.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-35",
    "name": "Semrush",
    "description": "أكاديمية Semrush لتعلم التسويق الرقمي. تقدم دورات مجانية في تحسين محركات البحث (SEO)، التسويق بالمحتوى، الإعلانات المدفوعة (PPC)، ووسائل التواصل الاجتماعي مع شهادات معتمدة.",
    "description_en": "Semrush Academy for digital marketing learning. Offers free courses in SEO, content marketing, PPC, and social media with accredited certificates.",
    "description_tr": "Dijital pazarlama \u00f6\u011frenimi i\u00e7in Semrush Akademisi. SEO, i\u00e7erik pazarlamas\u0131, PPC ve sosyal medya alanlar\u0131nda \u00fccretsiz kurslar sunar.",
    "category": "تسويق وأعمال",
    "platform": "Semrush",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://www.semrush.com/academy/",
    "thumbnail": "https://www.google.com/s2/favicons?domain=semrush.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-36",
    "name": "btkakademi.gov.tr",
    "description": "منصة التعليم التركية الرسمية من هيئة تقنية المعلومات والاتصالات. تقدم دورات مجانية في البرمجة، الأمن السيبراني، علم البيانات، الذكاء الاصطناعي، وتقنية المعلومات مع شهادات معتمدة.",
    "description_en": "Turkey's official education platform from the ICT Authority. Offers free courses in programming, cybersecurity, data science, AI, and IT with accredited certificates.",
    "description_tr": "BTK'n\u0131n resmi e\u011fitim platformu. Programlama, siber g\u00fcvenlik, veri bilimi, yapay zeka ve BT alanlar\u0131nda \u00fccretsiz kurslar ve sertifikalar sunar.",
    "category": "تكنولوجيا",
    "platform": "btkakademi.gov.tr",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "تركي",
    "link": "https://www.btkakademi.gov.tr/portal/courses",
    "thumbnail": "https://assets-btkakademi-gov-tr.akamaized.net/api/service/v1/public/51/assets/logo.png?ts=1738148275127",
    "startDate": ""
  },
  {
    "id": "plat-37",
    "name": "MATLAB Academy",
    "description": "أكاديمية MATLAB من MathWorks. تقدم دورات تفاعلية في MATLAB وSimulink ومعالجة الإشارات والصور والتعلم الآلي. بعض الدورات مجانية والأخرى مدفوعة.",
    "description_en": "MATLAB Academy by MathWorks. Offers interactive courses in MATLAB, Simulink, signal processing, image processing, and machine learning. Some courses are free, others paid.",
    "description_tr": "MathWorks'tan MATLAB Akademisi. MATLAB, Simulink, sinyal i\u015fleme, g\u00f6r\u00fcnt\u00fc i\u015fleme ve makine \u00f6\u011freniminde etkile\u015fimli kurslar sunar. Baz\u0131 kurslar \u00fccretsiz, baz\u0131lar\u0131 \u00fccretlidir.",
    "category": "برمجة وبيانات",
    "platform": "MATLAB Academy",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://matlabacademy.mathworks.com/?page=1&fq=course&sort=featured",
    "thumbnail": "https://www.google.com/s2/favicons?domain=mathworks.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-38",
    "name": "HubSpot Academy",
    "description": "أكاديمية HubSpot لتعلم التسويق والمبيعات وخدمة العملاء. تقدم دورات مجانية بالكامل مع شهادات معتمدة في التسويق الداخلي والتجارة الإلكترونية.",
    "description_en": "HubSpot Academy for learning marketing, sales, and customer service. Offers completely free courses with accredited certificates in inbound marketing and e-commerce.",
    "description_tr": "Pazarlama, sat\u0131\u015f ve m\u00fc\u015fteri hizmetleri i\u00e7in HubSpot Akademisi. Gelen pazarlama ve e-ticaret alanlar\u0131nda tamamen \u00fccretsiz kurslar sunar.",
    "category": "تسويق وأعمال",
    "platform": "HubSpot Academy",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "عربي/إنجليزي",
    "link": "https://academy.hubspot.com/courses?contentType=COURSE",
    "thumbnail": "https://www.google.com/s2/favicons?domain=hubspot.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-39",
    "name": "HackerRank",
    "description": "منصة عالمية للتحديات البرمجية واختبار المهارات. تقدم دورات تفاعلية ومشاريع عملية في Python، Java، SQL، والخوارزميات مع شهادات إتقان.",
    "description_en": "A global platform for coding challenges and skill testing. Offers interactive courses and hands-on projects in Python, Java, SQL, and algorithms with skill certificates.",
    "description_tr": "Kodlama zorluklar\u0131 ve beceri testi i\u00e7in k\u00fcresel bir platform. Python, Java, SQL ve algoritmalarda etkile\u015fimli kurslar ve beceri sertifikalar\u0131 sunar.",
    "category": "برمجة وبيانات",
    "platform": "HackerRank",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "إنجليزي",
    "link": "https://www.hackerrank.com/skills-verification",
    "thumbnail": "https://www.google.com/s2/favicons?domain=hackerrank.com&sz=128",
    "startDate": ""
  },
  {
    "id": "plat-40",
    "name": "كورسات",
    "description": "منصة عربية تقدم آلاف الدورات المجانية في مختلف المجالات مثل البرمجة والتصميم والتسويق والإدارة مع شهادات إتمام.",
    "description_en": "An Arab platform offering thousands of free courses in various fields like programming, design, marketing, and management with completion certificates.",
    "description_tr": "Programlama, tasar\u0131m, pazarlama ve y\u00f6netim gibi \u00e7e\u015fitli alanlarda binlerce \u00fccretsiz kurs sunan bir Arap platformu.",
    "category": "تعليم",
    "platform": "Coursat",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "عربي",
    "link": "https://www.coursat.org/categories",
    "thumbnail": "https://www.coursat.org/images/logo.png",
    "startDate": ""
  },
  {
    "id": "plat-41",
    "name": "Udemy",
    "description": "أكبر منصة تعليمية عالمية. تضم أكثر من 200 ألف دورة في جميع المجالات. الكثير من الدورات مجانية والأخرى مدفوعة بأسعار متفاوتة. تمنح شهادات إتمام للدورات المدفوعة.",
    "description_en": "The world's largest learning platform. Hosts over 200,000 courses in all fields. Many courses are free, others are paid at various prices. Offers completion certificates for paid courses.",
    "description_tr": "D\u00fcnyan\u0131n en b\u00fcy\u00fck \u00f6\u011frenme platformu. T\u00fcm alanlarda 200.000'den fazla kurs bar\u0131nd\u0131r\u0131r. Bir\u00e7ok kurs \u00fccretsiz, di\u011ferleri \u00e7e\u015fitli fiyatlarla \u00fccretlidir.",
    "category": "تعليم",
    "platform": "Udemy",
    "free": true,
    "certificate": true,
    "duration": "",
    "level": "",
    "language": "متعدد اللغات",
    "link": "https://www.udemy.com/courses/",
    "thumbnail": "https://www.google.com/s2/favicons?domain=udemy.com&sz=128",
    "startDate": ""
  },
];
